name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Create coverage directory
      run: mkdir -p coverage
    - uses: php-actions/phpunit@v3
      with:
        php_version: '8.2'
        php_extensions: "xdebug"
        coverage_clover: "coverage/clover.xml"
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/clover.xml
