name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6.1
          php_version: '8.2'
          php_extensions: gd mbstring pcov tokenizer
        if: success()

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        id: coverage_summary
        with:
          filename: log/coverage-cobertura.xml
      
      - name: Run PHPCS
        run: vendor/bin/phpcs --extensions=php ./lib/ --report=summary
        continue-on-error: true
      
      - name: Run PHPMD
        run: vendor/bin/phpmd ./lib ansi codesize,unusedcode,naming
        continue-on-error: true

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse ./lib/ --level=max
        continue-on-error: true
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: www/
          local-dir: ../
          exclude: |
            vendor/
